name: my first workflow
on:
  push:
jobs:
  starter job:
    runs-on: ubuntu-latest    
    steps:
      - name: check out the repository code
        uses: actions/checkout@4
      - name: Print directory listing
        run: ls
